### ISSUE TITLE
Extract nav into reusable component

### ISSUE THREAD

**Issue by wkentdag** [kchungradio/kchungradio.org#26]
@tim-phillips is there any reason why we couldn't turn this into a small React component? Or, if that violates the principle of having everything be static HTML, could we define it in one HTML file and add it to individual pages by cloning the element with JS?

**Comment by tim-phillips** [comment]
We do want to do this. 

I've been thinking a lot lately about adding a build step, which, you're right, would move us away from our goal of having everything be easy for people who only know HTML. That being said, our main content (stream, archive, schedule, posts) relies on JS, so that thought may be misguided to begin with. 

I'm leaning toward making our lives easier. I think something like [next.js](https://github.com/zeit/next.js) would be appropriate, but I'm willing to talk about our options. cc @LordNikon909 

Could you elaborate on the cloning with JS solution? I'm not clear on what it would look like.

**Comment by wkentdag** [comment]
I think JS would be cleaner but this isn't *too* hacky:

1. `nav.html` is accessible somewhere over http like `kchungradio.org/components/nav.html`
2. each page's html template has an empty `<nav />`
3. on page load, `fetch(nav.html)` and load the contents into the empty nav element.

That way it's defined in one place and is still static html, there's just some JS gluing it all together. If we want to go down this route, it wouldn't be too crazy to build some util functions to re-use this logic for other components and add some basic loading state too.

**Comment by tim-phillips** [comment]
Thanks for the explanation. 

Surprisingly, [on twitter yesterday](https://twitter.com/muanchiou/status/1186069266510036993) I saw some HTML centric frameworks mentioned: [stimulus](https://github.com/stimulusjs/stimulus) and [trimmings](https://github.com/postlight/trimmings). Maybe these are worth looking into?

@LordNikon909 and I talked about Vue since it's also a bit more HTML centric than React. I've never used anything worth using other than [vanilla](http://vanilla-js.com/) or React though so I don't really know how far that goes. I've just heard that React is hard to grok for people who aren't JS devs, which makes sense since you're learning two new things at once and they're hard to distinguish if you don't know where one ends and the other begins. 

Apple released their music app as a [web app](https://beta.music.apple.com) recently and [built it using ember and stencil](https://dev.to/ionic/apple-just-shipped-web-components-to-production-and-you-probably-missed-it-57pf) (which uses web components). Apparently [custom elements](https://developers.google.com/web/fundamentals/web-components/customelements) from web components can be [polyfilled](https://github.com/webcomponents/polyfills/tree/master/packages/custom-elements), so that takes care of the browser support. Stencil includes a built-in polyfill, but loads it only when needed. 

I guess the concerns are ease of developer onboarding, developer experience, and affecting people with slow devices. I guess we should measure before we assume that this even matters. We don't have any kind of analytics on the site, but we could add some. We can also think about our comfort levels since we're the ones actively working on this, and in our spare time, for free. So it might just make sense to do the easiest thing and not worry about the other stuff until we know it's a problem.

Thoughts?

**Comment by wkentdag** [comment]
I think that there's not much difference between Vue and JSX since at the end of the day, you'll need JS knowledge to deal with either one (even if you're just building with webpack).

Web components seem like an interesting middle ground. I don't have any experience with them. It might be a good fit for the nav, since unlike the calendar or other React widgets, it's totally dumb. I'll do some research this week and report back.

**Comment by wkentdag** [comment]
I also think this would be a topic worth discussing at the next staff meeting - if there's nobody currently on staff who knows HTML but not JS, it might be a moot point!

**Comment by tim-phillips** [comment]
Staff meetings are the 3rd Sunday of each month, there's usually an email a few days before to confirm it

**Comment by tim-phillips** [comment]
These sites have a good list of possible contenders:

https://www.staticgen.com/
https://zeit.co/docs/v2/build-step/#optimized-frameworks
