### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by wkentdag** [kchungradio/kchungradio.org#27]
It would be cool to have Analytics to have a better sense of our site audience. Ideally, a non-Google Analytics setup, something like this:

https://benhoyt.com/writings/replacing-google-analytics/

**Comment by tim-phillips** [comment]
@birthdaycorp #79

**Comment by birthdaycorp** [comment]
@tim-phillips i created #81 to address this. <del>i was able to confirm activity on my local, but the test environment is not loading the scripts. perhaps it needs to be rebuilt so that it takes the new env variables?</del>

the preview environment is loading the scripts, but the PR needs another reviewer to merge. can you check it out when you have the time?

**Comment by tim-phillips** [comment]
@birthdaycorp yeah, we'll need to add the env vars to vercel. can you hmu on slack and we'll sort that out?

**Comment by tim-phillips** [comment]
Resolved by #81
